### ISSUE TITLE
CrunchDAO details

### ISSUE THREAD

**Issue by matteoettam09** [TheSCInitiative/DeSci-Community-Resources#4]
Here is the invite link for our Discord:

https://discord.gg/x7kFex8G

And here is the description:

CrunchDAO is a Decentralized Autonomous Organization of scientists making use of collective intelligence to solve complex problems. Focusing on quantitative finance, it makes use of DeSci as a tool to coordinate its members.

**Comment by jring-o** [comment]
Added. Thanks!
